### ISSUE TITLE
Please provide Changelog

### ISSUE THREAD

**Issue by wolasss** [smsapi/smsapi-javascript-client#15]
Please provide a changelog so that one could determine what kind of changes are released with new versions. 

Are there any breaking API changes with the 2.0 release? 

(You may consider using `semantic-release` to manage versioning)

**Comment by smsapi** [comment]
Hello! Thanks for your input. We have decided to follow your advice and create a CHANGELOG file with brief description of changes introduced in version 2, as well as more elaborate description for minor version. We also intend to maintain this changelog in future versions of smsapi-javascript-client.
