### ISSUE TITLE
Can't really use ProxyAbstract

### ISSUE THREAD

**Issue by Froelund** [smsapi/smsapi-javascript-client#3]
As I understand, `ProxyAbstract` is exposed by `smsapi.js`, in order to provide a method for implementing a custom class, that has a request method, which returns an instance of `lib/Request`.

My issue is that `lib/Request` is not exposed on `lib/smsapi`, so I can't really return an instance of this private library class.

**Comment by Froelund** [comment]
My initial issue, is that I want requests to smsapi to go through our company http-proxy. Common use-case I guess.

**Comment by sheldarr** [comment]
We exposed `lib/Request` via `SMSAPI` because as you mentioned it must be returned by `ProxyAbstract` request method. Now you should be able to write your custom implementation of ProxyAbstract.

**Comment by Froelund** [comment]
Yes - That's what I ended up doing 👍 
However it's confusing that `ProxyAbstract` is exposed directly on library, and Request is found in lib.
I ended with this for proxying http requests.
```
require('superagent-proxy')(require('superagent')); //Patches superagent with a proxy method. superagent is used by smsapicom, and needs to be directed through our proxy
const SMSAPI = require('smsapicom');
const SMSAPIProxyHttp = require('smsapicom/lib/proxy-http')
const SMSAPIRequest = require('smsapicom/lib/request');

function ProxyRequest(options) {
  SMSAPIRequest.call(this, options);
  this._httpProxyUrl = options.httpProxyUrl;
}
  
ProxyRequest.prototype._createRequest = function () {
  const origRequest = SMSAPIRequest.prototype._createRequest.call(this);
  if (this._httpProxyUrl) origRequest.proxy(this._httpProxyUrl);
  return origRequest;
}
  
function HttpProxy(options) {
  SMSAPIProxyHttp.call(this, options);
  this._httpProxyUrl = options.httpProxyUrl;
}
  
HttpProxy.prototype = Object.create(SMSAPIProxyHttp.prototype);
  
/**
 * create a new request
 * @return {Request}
 */
HttpProxy.prototype.request = function () {
  return new ProxyRequest({
    server: this._server,
    auth: this._auth,
    httpProxyUrl: this._httpProxyUrl,
  });
};

module.exports = function createClient(options) {
  return new SMSAPI(Object.assign({}, options, {
    proxy: new HttpProxy({
      server: options.server,
      httpProxyUrl: options.httpProxyUrl,
    }),
  }))
}
```

If you have a better solution for using company proxy, please let me know :)
