### ISSUE TITLE
Please provide typescript .d.ts typings

### ISSUE THREAD

**Issue by Jblew** [smsapi/smsapi-javascript-client#5]
Please provide a typescript .d.ts typings for the library. Typescript is gaining popularity very quickly, and it is a great solution for critical apps as it prevents many mistakes at a very early stage of development. SMS sending is indeed a critical part of an app as it has both money and direct user experience involved. Thanks!

**Comment by smsapi** [comment]
Hello! We have introduced Typescript support starting from version 2.0.0. Just use the latest version, since we were already able to fix some issues.
